part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN = _Paths.LOGIN;
  static const FORGET_PASSWORD = _Paths.FORGET_PASSWORD;
  static const NEW_PASSWORD = _Paths.NEW_PASSWORD;
  static const REGISTRATION = _Paths.REGISTRATION;
  static const HOME = _Paths.HOME;
  static const MESSAGE = _Paths.MESSAGE;
  static const CREATE_POST = _Paths.CREATE_POST;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const PROFILE = _Paths.PROFILE;
  static const FAVORITE_LIST = _Paths.FAVORITE_LIST;
  static const CALL_HISTORY = _Paths.CALL_HISTORY;
  static const PURCHASE_HISTORY = _Paths.PURCHASE_HISTORY;
  static const FACE_VERIFICATION = _Paths.FACE_VERIFICATION;
  static const ABOUT_US = _Paths.ABOUT_US;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const ACCOUNT_SETTINGS = _Paths.ACCOUNT_SETTINGS;
  static const NOTIFICATION_SETTINGS = _Paths.NOTIFICATION_SETTINGS;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const ILU_POINT = _Paths.ILU_POINT;
  static const OTP_VERIFICATION = _Paths.OTP_VERIFICATION;
  static const DETAILS_PROFILE = _Paths.DETAILS_PROFILE;
  static const MY_TIMELINE = _Paths.MY_TIMELINE;
  static const BLOCK_LIST = _Paths.BLOCK_LIST;
  static const CHAT = _Paths.CHAT;
  static const REWARD_HISTORY = _Paths.REWARD_HISTORY;
  static const WITHDRAW_HISTORY = _Paths.WITHDRAW_HISTORY;
  static const WITHDRAW_REWARD_POINT = _Paths.WITHDRAW_REWARD_POINT;
  static const BANK_WITHDRAW = _Paths.BANK_WITHDRAW;
  static const BKASH_WITHDRAW = _Paths.BKASH_WITHDRAW;
  static const NAGAD_WITHDRAW = _Paths.NAGAD_WITHDRAW;
  static const REGISTRATION_OTP = _Paths.REGISTRATION_OTP;
  static const INVOICE_DETAILS = _Paths.INVOICE_DETAILS;
  static const DETAILS_IMAGES = _Paths.DETAILS_IMAGES;
  static const HELP_AND_SUPPORT = _Paths.HELP_AND_SUPPORT;
  static const TERMS_AND_CONDITIONS = _Paths.TERMS_AND_CONDITIONS;
  static const VIDEOCALL = _Paths.VIDEOCALL;
  static const AUDIO_CALL = _Paths.AUDIO_CALL;
  static const EDIT_POST = _Paths.EDIT_POST;
  static const RECHARGE_DIRECTLY = _Paths.RECHARGE_DIRECTLY;
  static const RECHARGE_FROM_REWARD_BALANCE =
      _Paths.RECHARGE_FROM_REWARD_BALANCE;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const LOGIN = '/login';
  static const FORGET_PASSWORD = '/forget-password';
  static const NEW_PASSWORD = '/new-password';
  static const REGISTRATION = '/registration';
  static const HOME = '/home';
  static const MESSAGE = '/message';
  static const CREATE_POST = '/create-post';
  static const NOTIFICATION = '/notification';
  static const PROFILE = '/profile';
  static const FAVORITE_LIST = '/favorite-list';
  static const CALL_HISTORY = '/video_call-history';
  static const PURCHASE_HISTORY = '/purchase-history';
  static const FACE_VERIFICATION = '/face-verification';
  static const ABOUT_US = '/about-us';
  static const EDIT_PROFILE = '/edit-profile';
  static const ACCOUNT_SETTINGS = '/account-settings';
  static const NOTIFICATION_SETTINGS = '/notification-settings';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const ILU_POINT = '/ilu-point';
  static const OTP_VERIFICATION = '/otp-verification';
  static const DETAILS_PROFILE = '/details-profile';
  static const MY_TIMELINE = '/my-timeline';
  static const BLOCK_LIST = '/block-list';
  static const CHAT = '/chat';
  static const REWARD_HISTORY = '/reward-history';
  static const WITHDRAW_HISTORY = '/withdraw-history';
  static const WITHDRAW_REWARD_POINT = '/withdraw-reward-point';
  static const BANK_WITHDRAW = '/bank-withdraw';
  static const BKASH_WITHDRAW = '/bkash-withdraw';
  static const NAGAD_WITHDRAW = '/nagad-withdraw';
  static const REGISTRATION_OTP = '/registration-otp';
  static const INVOICE_DETAILS = '/invoice-details';
  static const DETAILS_IMAGES = '/details-images';
  static const HELP_AND_SUPPORT = '/help-and-support';
  static const TERMS_AND_CONDITIONS = '/terms-and-conditions';
  static const VIDEOCALL = '/video_call';
  static const AUDIO_CALL = '/audio-call';
  static const EDIT_POST = '/edit-post';
  static const RECHARGE_DIRECTLY = '/recharge-directly';
  static const RECHARGE_FROM_REWARD_BALANCE = '/recharge-from-reward-balance';
}
